version:     "001--12-Sep-2022"
copyright:   "2022"
author:      "Inaya Rahmanisa"
title:       "OS222: Operating Systems 2022-2"
githublink:  "https://github.com/inayarhmns/os222/"
myloglink:   "/TXT/mylog.txt"
mypublickey: "/TXT/mypubkey.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
